import { ProposalModel, ProposalStatus } from 'app/models/ProjectProposalModel'
import { UserTypes } from 'app/models/UserModel'

export const fakeProposals: ProposalModel[] = [
  {
    id: 0,
    name: 'Название проекта',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales orci sit amet tempus hendrerit. Suspendisse vestibulum quis nulla quis imperdiet. Suspendisse ornare, sem et euismod volutpat, velit lectus pellentesque felis, et dignissim turpis augue vel justo. Vestibulum eleifend gravida aliquam.',
    purpose: 'Ut in dui vitae justo tincidunt accumsan ac ac lacus. Suspendisse accumsan, enim sed pretium eleifend, ante risus rutrum lorem, sit amet sollicitudin felis urna a tellus. Suspendisse potenti. In tincidunt nisi vitae gravida vulputate. Quisque vitae erat leo.',
    result: 'Duis condimentum, sem sed facilisis laoreet, est magna aliquam sapien, sit amet laoreet dolor enim ut velit.',
    contacts: 'Иванов Иван Иванович - 89990990909\nАндреев Николай - a.d.asd@mail.com',
    curator: 'Хлебников Н.А.',
    organization: 'УрФУ',
    teamCapacity: 5,
    maxTeamCount: 3,
    lifeScenarioName: 'Крутая',
    keyTechnologyName: 'Прикольная',
    author: {
      id: 0,
      lastName: 'Иванов',
      firstName: 'Иван',
      middleName: 'Иванович',
      about: 'Что-то тут написано',
      login: 'Ivanov',
      email: 'Ivanov@mail.ru',
      phoneNumber: '+79221111111',
      academicGroup: 'РИ-380000',
      userType: UserTypes.Student,
    },
    status: ProposalStatus.Approved,
    date: new Date().toString(),
  },
  {
    id: 1,
    name: 'Название проекта 2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales orci sit amet tempus hendrerit. Suspendisse vestibulum quis nulla quis imperdiet. Suspendisse ornare, sem et euismod volutpat, velit lectus pellentesque felis, et dignissim turpis augue vel justo. Vestibulum eleifend gravida aliquam.',
    purpose: 'Ut in dui vitae justo tincidunt accumsan ac ac lacus. Suspendisse accumsan, enim sed pretium eleifend, ante risus rutrum lorem, sit amet sollicitudin felis urna a tellus. Suspendisse potenti. In tincidunt nisi vitae gravida vulputate. Quisque vitae erat leo.',
    result: 'Duis condimentum, sem sed facilisis laoreet, est magna aliquam sapien, sit amet laoreet dolor enim ut velit.',
    contacts: 'Иванов Иван Иванович - 89990990909\nАндреев Николай - a.d.asd@mail.com',
    curator: 'Хлебников Н.А.',
    organization: 'УрФУ',
    teamCapacity: 4,
    maxTeamCount: 4,
    lifeScenarioName: 'Крутая',
    keyTechnologyName: 'Прикольная',
    author: {
      id: 1,
      lastName: 'Иванов',
      firstName: 'Иван',
      middleName: 'Иванович',
      about: 'Что-то тут написано',
      login: 'Ivanov',
      email: 'Ivanov@mail.ru',
      phoneNumber: '+79221111111',
      academicGroup: 'РИ-380000',
      userType: UserTypes.Admin,
    },
    status: ProposalStatus.Rejected,
    date: new Date().toString(),
  },
  {
    id: 2,
    name: 'Название проекта 3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales orci sit amet tempus hendrerit. Suspendisse vestibulum quis nulla quis imperdiet. Suspendisse ornare, sem et euismod volutpat, velit lectus pellentesque felis, et dignissim turpis augue vel justo. Vestibulum eleifend gravida aliquam.',
    purpose: 'Ut in dui vitae justo tincidunt accumsan ac ac lacus. Suspendisse accumsan, enim sed pretium eleifend, ante risus rutrum lorem, sit amet sollicitudin felis urna a tellus. Suspendisse potenti. In tincidunt nisi vitae gravida vulputate. Quisque vitae erat leo.',
    result: 'Duis condimentum, sem sed facilisis laoreet, est magna aliquam sapien, sit amet laoreet dolor enim ut velit.',
    contacts: 'Иванов Иван Иванович - 89990990909\nАндреев Николай - a.d.asd@mail.com',
    curator: 'Хлебников Н.А.',
    organization: 'УрФУ',
    teamCapacity: 6,
    maxTeamCount: 3,
    lifeScenarioName: 'Крутая',
    keyTechnologyName: 'Прикольная',
    author: {
      id: 2,
      lastName: 'Алексеев',
      firstName: 'Алексей',
      middleName: 'Алексеевич',
      about: 'Что-то тут написано',
      login: 'Aleksey',
      email: 'Aleksey@mail.ru',
      phoneNumber: '+79221111111',
      academicGroup: 'РИ-380000',
      userType: UserTypes.Student,
    },
    status: ProposalStatus.Pending,
    date: new Date().toString(),
  },
  {
    id: 3,
    name: 'Название проекта 4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales orci sit amet tempus hendrerit. Suspendisse vestibulum quis nulla quis imperdiet. Suspendisse ornare, sem et euismod volutpat, velit lectus pellentesque felis, et dignissim turpis augue vel justo. Vestibulum eleifend gravida aliquam.',
    purpose: 'Ut in dui vitae justo tincidunt accumsan ac ac lacus. Suspendisse accumsan, enim sed pretium eleifend, ante risus rutrum lorem, sit amet sollicitudin felis urna a tellus. Suspendisse potenti. In tincidunt nisi vitae gravida vulputate. Quisque vitae erat leo.',
    result: 'Duis condimentum, sem sed facilisis laoreet, est magna aliquam sapien, sit amet laoreet dolor enim ut velit.',
    contacts: 'Иванов Иван Иванович - 89990990909\nАндреев Николай - a.d.asd@mail.com',
    curator: 'Хлебников Н.А.',
    organization: 'УрФУ',
    teamCapacity: 6,
    maxTeamCount: 3,
    lifeScenarioName: 'Крутая',
    keyTechnologyName: 'Прикольная',
    author: {
      id: 3,
      lastName: 'Алексеев',
      firstName: 'Алексей',
      middleName: 'Алексеевич',
      about: 'Что-то тут написано',
      login: 'Aleksey',
      email: 'Aleksey@mail.ru',
      phoneNumber: '+79221111111',
      academicGroup: 'РИ-380000',
      userType: UserTypes.Expert,
    },
    status: ProposalStatus.Approved,
    date: new Date().toString(),
  },
]
